name: ppo

train_every: 32
ppo_epochs: 10
num_minibatches: 5
clip_param: 0.2
entropy_coef: 0.001
gae_lambda: 0.95
gamma: 0.99
max_grad_norm: 5.0

# whether to use privileged information
priv_actor: false
priv_critic: false

checkpoint_path:

actor:
  lr: 0.0005
  lr_scheduler:
  lr_scheduler_kwargs:

  # mlp
  hidden_units: [128, 128, 128]
  activation: relu  # relu, leaky_relu, elu, gelu, tanh, silu
  layer_norm: true

  weight_decay: 0.0

critic:
  lr: 0.0005
  lr_scheduler:
  lr_scheduler_kwargs:

  # mlp
  hidden_units: [128, 128, 128]
  activation: relu  # relu, leaky_relu, elu, gelu, tanh, silu
  layer_norm: true

  weight_decay: 0.0
  use_huber_loss: false
  huber_delta: 10.0